# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d5962bc0dc21a29b81ef1fe707ec6a36d4303235b8c3cafd523801b5c364b17cc4036c15dfcc15528b889f19547c7a0fdc55b5b37cf3a495c832b9e35e502e2

test:
  secret_key_base: acd30e39d981a2ceccdd403910491e3bc335d2410b139a5ec7cc534254c93cb861d227f299798b647ec038d55c59831df0a3cfb980359ebbcdf0049a9a51f2c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
